language: go
sudo: false

go:
 - 1.7.x
 - 1.7

services:
 - redis-server

before_install:
 - go get github.com/mattn/goveralls

install:
 - go get -t ./...

script:
 - go test -v ./...

after_script:
 - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email: false